This section will provide information regarding on how to include common country specific data in PUF.

The aim for PUF is to cover business requirements in legal domains and countries all over the world.

The below list should be seen as an overview to visualize where PUF currently is considered applicable.

If the country is marked as supported means that an analysis of country or regional requirements has been made.

*It does not*, however, automatically mean that all conceivable content requirements are supported within PUF.

If a country is not in the list it does not necessarily mean that PUF cannot be used in the specific region but it means that no extensive analysis has been done of the requirements.

The list of supported countries/regions are updated continuously as PUF is developed to follow new identified markets/requirements.

=== Supported countries

The following list gives an overview of country support in PUF Clearance Notification.

NOTE: Refer to the example files to see typical values that can be provided in each country/region

.Table of supported countries
[%autowidth.stretch]
|===
|Country |Clearance notification |Tax report notification|Comment

|Greece
|*Yes*
|-
|-

|Hungary
|*Yes*
|-
|-


|India
|*Yes*
|-
|-

|Israel
|*Yes*
|-
|-

|Poland
|*Yes*
|-
|-

|Saudi Arabia
|*Yes*
|-
|-

|Serbia
|*Yes*
|-
|-

|Singapore
|-
|*Yes*
|*Beta version only*


|Spain (Basque Country)
|*Yes*
|-
|Support for TicketBAI system in the Basque region.

|===
