PUF Clearance Notification is a message type that is applicable to be exchanged in Clearance and CTC markets between Pagero and Issuer of an Invoice. It will inform issuer of the clearance/reporting status (i.e. rejected or accepted) but can also contain clearance artefacts such as QR codes or a signed cleared document.

PUF Clearance notification is developed to be compliant to the https://docs.oasis-open.org/ubl/UBL-2.3.html[UBL 2.3] structure.

In areas where support for certain information is available in the existing https://docs.oasis-open.org/ubl/UBL-2.3.html[UBL 2.3] structure, PUF implements these elements.

In other areas where there are no suitable elements in the existing https://docs.oasis-open.org/ubl/UBL-2.3.html[UBL 2.3] schema, PUF implements `ext:UBLExtensions`.

=== How to get started with PUF Clearance Notification

In the following chapters you can see which elements and what type of information that PUF Clearance Notification supports. 

In some cases you will also get longer snippets of code and implementation guidelines in order how to properly interpret the data. 

There is also a section with <<_examples>> that can be useful when building support for PUF Clearance Notification in various markets.

If your ERP system already can receive documents in https://docs.oasis-open.org/ubl/UBL-2.3.html[UBL 2.3] or if your ERP system can interpret a UBL based format you can easily use this as stepping stone when moving towards PUF.


=== Namespaces

*Target root name space - ApplicationResponse:* 

- `urn:oasis:names:specification:ubl:schema:xsd:ApplicationResponse-2` +

*Example:* +
_ApplicationResponse example for target namespace_
[source,xml]
----
<ApplicationResponse xmlns="urn:oasis:names:specification:ubl:schema:xsd:ApplicationResponse-2">
  <!-- Code omitted for clarity -->
</ApplicationResponse>
----


=== Customization and Profile ID

To indicate the correct PUF specification identifer and the profile identifier, the values in below table must be sent in `cbc:CustomizationID` and `cbc:ProfileID`.

[%autowidth.stretch]
|===
|Type |Element `cbc:CustomizationID` |Element `cbc:ProfileID`

|*Clearance Notification*
|urn:pagero.com:puf:clearance_notification:1.0
|urn:pagero.com:puf:clearance_notification:1.0
|===

*Example of CustomizationID and ProfileID:*
[source,xml]
----
<cbc:CustomizationID>urn:pagero.com:puf:clearance_notification:1.0</cbc:CustomizationID>
<cbc:ProfileID>urn:pagero.com:puf:clearance_notification:1.0</cbc:ProfileID>
----

=== Working with extensions

This chapter provides an overview the use of extensions.

In order to facilitate the use of PUF specific extensions, a schema for the extensions is provided.

The `PUF-ExtensionComponent.xsd` can be found together with the other schemas in chapter <<_xml_schemas>>. 

To be able to use the `PUF-ExtensionComponent` a namespace must be included in the document file.

*Example* +
_Example from ApplicationResponse_
[source,xml]
----
<ApplicationResponse ... xmlns:puf="urn:pagero:ExtensionComponent:1.0">
  <!-- Code omitted for clarity -->
</ApplicationResponse>
----

Depending on in which context the `UBLExtensions` are used there are different options of what types of values that can be provided.

To identify which context the `UBLExtensions` is in the element ExtensionURI is used. 

When using these Pagero extensions, the URI has the same base:

- `urn:pagero:ExtensionComponent:1.0:PageroExtension`

After the URI, the specific resource name is added.

*Example* +
_UBLExtension used in the cac:Response structure._
[source,xml]
----
<cac:Response>
      <ext:UBLExtensions>
          <ext:UBLExtension>
              <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:ResponseExtension</ext:ExtensionURI>
              <!-- Code omitted for clarity -->
</cac:Response>
----

For detailed examples and how to use possible values in each extension please check the chapters where the PUF-specific elements are described.

=== Release management

PUF will be continuously updated to meet new market demands. 

==== Minor release

A minor release will always be backward compatible and will take place without prior notice and will be implemented whenever needed. 

Minor releases may include bugfixes, new elements, schematron updates and other features. 

These releases can be followed on https://github.com/pagero/puf[GitHub].

==== Major release

A major release may include changes that are not backward compatible. 

Such a release will be notified at least three months prior to date of implementation, to users who registered an account on Pagero validex or on https://github.com/pagero/puf[GitHub].

To register for PUF major release notification you can create a free account on https://pagero.validex.net[Pagero Validex]. 

But we urge all interested parties to follow the project on https://github.com/pagero/puf[GitHub] where all releases will be notified.
