==== puf:ResponseExtension

Below table shows the definition of elements added to the extension `puf:PageroExtension/puf:ResponseExtension`.

.Elements added in puf:ResponseExtension
|===
|Element |Description

|`puf:RestrictedInformation/puf:Key`
|**Key** +
Key defining the type of value.

|`puf:RestrictedInformation/puf:Value`
|**Value** +
Value relevant to the assigned key.

|`puf:ReferencedDocumentInterchangeID/cbc:ID`
| **Referenced document unique ID** +
The interchange id of the referenced document (if sent by the issuer).

|`puf:AuthorityDeliveryDateTime`
| **Authority delivery date and time** +
The date and time the tax report was sent to the authority.

|`puf:ClearanceReferenceID/cbc:ID`
|**Clearance reference ID** +
The ID generated by the clearance authority or an ID used to reference the invoice at clearance authority.

|`puf:ClearanceQR/puf:QRString`
|**Clearance QR code** +
The QR string as generated by clearance authority. 

|`puf:AdditionalDocumentReference/cbc:ID`
|**Additional document reference id** +
If there are any attachments that relates to the response. +
Identifier of the additional document reference.

|`puf:AdditionalDocumentReference/cbc:DocumentTypeCode`
|**Additional document type code** +
Type of attachment. + 
**M** = Miscellaneous

|`puf:AdditionalDocumentReference/cbc:DocumentDescription`
|**Additional document description** +
Description of the attached document.

|`puf:AdditionalDocumentReference/cac:Attachment/ + 
cbc:EmbeddedDocumentBinaryObject/@filename`
|**Additional document filename** +
Filename of the attached document.

|`puf:AdditionalDocumentReference/cac:Attachment/ + 
cbc:EmbeddedDocumentBinaryObject/@mimeCode`
|**Additional document MIME code** +
MIME code of the attached document. + 
Supported MIME codes can be found in the code list +
https://pagero.github.io/puf-code-lists/#_puf_006_mimecodes[PUF-006-MIMECODES^].

|`puf:AdditionalDocumentReference/cac:Attachment/ + 
cbc:EmbeddedDocumentBinaryObject`
|**Additional document binary object** +
The attached document embedded as binary object (Base64).

|===

See example below as well as the URI to be used for this extension.

*Example* +
_puf:ResponseExtension with sample values._
[source,xml]
----
<ApplicationResponse>
  <!-- Code omitted for clarity -->
  <cac:DocumentResponse>
    <cac:Response>
      <ext:UBLExtensions>
        <ext:UBLExtension>
          <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:ResponseExtension</ext:ExtensionURI>
          <ext:ExtensionContent>
              <puf:PageroExtension>
                <puf:ResponseExtension>
                  <puf:RestrictedInformation>
                    <puf:Key>TheKey</puf:Key>
                    <puf:Value>TheValue</puf:Value>
                  </puf:RestrictedInformation>
                  <puf:ReferencedDocumentInterchangeID>
                    <cbc:ID>123456789</cbc:ID>
                  </puf:ReferencedDocumentInterchangeID>
                  <puf:AuthorityDeliveryDateTime>2025-01-01T18:00:00.000Z</puf:AuthorityDeliveryDateTime>
                  <puf:ClearanceReferenceID>
                    <cbc:ID>4543f3ed-8c20-4eee-a19f-486025fe2773</cbc:ID>
                  </puf:ClearanceReferenceID>
                  <puf:ClearanceQR>
                    <puf:QRString>VGhlIFFSIENvZGU=</puf:QRString>
                  </puf:ClearanceQR>
                  <puf:AdditionalDocumentReference>
                    <cbc:ID>1456123</cbc:ID>
                    <cbc:DocumentTypeCode>M</cbc:DocumentTypeCode>
                    <cbc:DocumentDescription>LCD</cbc:DocumentDescription>
                    <cac:Attachment>
                      <cbc:EmbeddedDocumentBinaryObject filename="123456789_12345.xml" mimeCode="application/xml">U29tZSBkb2N1bWVudA==</cbc:EmbeddedDocumentBinaryObject>
                    </cac:Attachment>
                  </puf:AdditionalDocumentReference>
                </puf:ResponseExtension>
              </puf:PageroExtension>
          </ext:ExtensionContent>
        </ext:UBLExtension>
      <ext:UBLExtensions>
    </cac:Response>    
  <!-- Code omitted for clarity -->
</ApplicationResponse>
----
